log:
  # Use debug to output executed restic commands
  level: "info"

# Repositories configuration
repositories:
  - name: "RepositoryName"
    url: "./repository" # https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html
    password: "password"
    password_file: "path/to/file"
    env_from_file: 
      var1: "path/to/file"
      var2: "path/to/file"
    env: 
      test: "test"
    auto_initialize: true

    backup:
      schedule: "* * * * *"
      run_on_startup: true
      include_files:
        - /files
        - /data
      exclude_files:
        - /data/*.tmp

    integrity_check:
      schedule: "* * * * *"
      run_on_startup: true
    
    retention:
      schedule: "* * * * *"
      run_on_startup: true
      policy:
        keep_last: 1
        keep_hourly: 1
        keep_daily: 3
        keep_weekly: 1
        keep_monthly: 1
        keep_yearly: 1
        # Keep snapshots with tag1 OR tag2
        # keep_tags: ["tag1", "tag2"]
        # Keep snapshots with tag1 AND tag2
        # keep_tags: ["tag1,tag2"]
        keep_within: "3y1m2d"

    rsync:
      schedule: "* * * * *"
      user: "user"
      host: "remote.example.com"
      target_folder: "backups"
      port: 22